// Jaun Store - Central Catalog
const JAUN_STORE_DATA = [
  {
    id: "fb-auto-warmup",
    title: "Jaun Warmup VIP",
    subtitle: "FB Reels & Reaction Bot",
    category: "extensions",
    subCategory: "facebook",
    type: "Chrome Extension (Manifest V3)",
    price: "FREE",
    isFree: true,
    isFeatured: true,
    version: "v2.0.0",
    icon: "assets/icons/warmup/icon128.png",
    downloadUrl: "https://drive.google.com/drive/folders/1eg0Nnt5oOWMiIYqDZth4b1_cWwxAk_bY?usp=sharing",
    downloadFilename: "fb-auto-warmup-extension",
    fileSize: "Google Drive Cloud",
    rating: 5.0,
    reviewsCount: 142,
    shortDesc: "Auto Facebook Reels 15s Watcher, Auto Reactions (Like/Love/Haha) & Smart Reel Switcher with Niche Keyword targeting.",
    longDesc: "Jaun Warmup VIP Edition is engineered specifically for Facebook accounts and pages warmup. It simulates authentic human viewing behavior by automatically watching Facebook Reels for 15 seconds, dispensing natural humanized reactions (Like, Love, Haha, Wow), and switching to the next reel with randomized intervals. Fully compliant with Chrome Manifest V3 and runs seamlessly inside the native Chrome Side Panel.",
    badges: ["FREE", "FEATURED", "GOOGLE DRIVE", "SIDE PANEL", "MANIFEST V3"],
    features: [
      "Auto 15-Second Reels & Video Watch Timer",
      "Humanized Smart Reactions: Like, Love, Haha, Wow",
      "Niche Keyword AI Targeting & Feed Search",
      "Native Chrome Side Panel Integration",
      "Anti-Detection Algorithm with Random Intervals",
      "1-Click Start / Pause / Stop Session Controls"
    ],
    techStack: ["JavaScript", "Chrome Extensions API", "Manifest V3", "Side Panel API"],
    installGuide: {
      step1: "Click 'Download Free' to open Google Drive and download the extension files / folder.",
      step2: "Save / Unzip the downloaded folder to any permanent location (e.g. D:\\my project\\fb-auto-warmup-extension).",
      step3: "Open Google Chrome and navigate to chrome://extensions in the address bar.",
      step4: "Enable 'Developer mode' toggle in the top-right corner.",
      step5: "Click 'Load unpacked' in the top-left corner and select the extension folder. The extension will appear instantly!"
    }
  },
  {
    id: "jaun-bulk-download",
    title: "Jaun Bulk Download VIP",
    subtitle: "Public Release — 4K Full HD Multi-Batch Downloader",
    category: "desktop",
    subCategory: "video",
    type: "Windows Desktop Application (.EXE)",
    price: "RS 560",
    priceSubtitle: "Lifetime With Update",
    isFree: false,
    isPaid: true,
    isFeatured: true,
    version: "v3.2.0 VIP Edition",
    icon: "assets/icons/downloader/logo.png",
    whatsappNumber: "03361849934",
    whatsappLink: "https://wa.me/923361849934?text=Salam%20Jaun,%20Mujhe%20Jaun%20Bulk%20Download%20VIP%20(RS%20560%20Lifetime%20With%20Update)%20chahiye.",
    rating: 5.0,
    reviewsCount: 220,
    shortDesc: "High-speed multithreaded video downloader for Facebook Reels, Pages, YouTube, and TikTok in 1080p / 4K without watermarks.",
    longDesc: "Official Public Release of Jaun Bulk Download VIP. Download entire Facebook pages, video libraries, reels, and YouTube/TikTok playlists in bulk with ultra high speed. Strips watermarks, extracts real video titles, and guarantees zero compression loss. Includes Lifetime License with free future updates and free dedicated WhatsApp support.",
    badges: ["RS 560 LIFETIME", "WITH UPDATE", "FREE SUPPORT", "ORDER ON WHATSAPP"],
    features: [
      "Bulk Download Entire Facebook Pages & Reel Libraries",
      "YouTube, TikTok, Instagram & Twitter High-Speed Ingestion",
      "Lossless 1080p & 4K 60FPS Without Watermarks",
      "Auto Clean Title Extraction and File Sanitization",
      "Lifetime License with Automatic Future Updates",
      "Free VIP Customer Support via WhatsApp: 03361849934"
    ],
    techStack: ["Electron", "Node.js", "yt-dlp Turbo", "FFmpeg Engine", "Windows x64"],
    actionType: "buy_on_whatsapp"
  },
  {
    id: "jaun-2fn",
    title: "Jaun 2FN",
    subtitle: "Ultra-Secure Online & Offline TOTP 2FA Authenticator",
    category: "webapps",
    subCategory: "security",
    type: "Web Application & Security Suite",
    price: "FREE",
    isFree: true,
    isFeatured: true,
    version: "v2.5 Live",
    icon: "assets/icons/2fn/logo.jpg",
    liveUrl: "https://jaun-2-fn.vercel.app/",
    rating: 5.0,
    reviewsCount: 310,
    shortDesc: "Military-grade privacy-first 2FA TOTP code generator compatible with Google Authenticator, Binance, Facebook, and Telegram.",
    longDesc: "Official web deployment of Jaun 2FN. A high-performance, ultra-secure two-factor authenticator (TOTP) that works 100% client-side with zero external servers. Full compatibility with Google Authenticator, Authy, Microsoft Authenticator, GitHub, Binance, and Meta accounts. Features instant 1-click token generation, live countdown timer, and offline functionality.",
    badges: ["FREE", "LIVE WEB APP", "VERCEL HOSTED", "MILITARY ENCRYPTION"],
    features: [
      "100% Client-Side Web Crypto with Zero Server Data Storage",
      "Full Compatibility with Google Authenticator & Authy",
      "Works 100% Offline with Instant 30s TOTP Token Calculation",
      "High-Speed 1-Click Copy with Dynamic Visual Progress Timer",
      "Compatible with Binance, Facebook, GitHub, Telegram & Google",
      "Clean Dark Obsidian UI with Neon Security Accents"
    ],
    techStack: ["JavaScript", "Web Crypto API", "TOTP RFC 6238", "Vercel Edge"],
    actionType: "open_web_app"
  },
  {
    id: "fb-vip-autouploader",
    title: "FB VIP Auto-Uploader Suite",
    subtitle: "Flagship Multi-Page 24/7 Loop Publisher",
    category: "upcoming",
    subCategory: "facebook",
    type: "Windows Desktop Software (.EXE)",
    price: "RS 5,000",
    originalPrice: "RS 16,500",
    priceSubtitle: "1-Year Plan (70% OFF Advance Booking)",
    isFree: false,
    isUpcoming: true,
    hasAdvanceBooking: true,
    launchCountdown: "Launching Within 7 Days",
    isFeatured: true,
    version: "v3.0.0 VIP Release",
    icon: "assets/icons/uploader-icon.svg",
    localFolder: "D:\\my project\\fb automation",
    whatsappNumber: "03361849934",
    whatsappLink: "https://wa.me/923361849934?text=Salam%20Jaun,%20Mujhe%20FB%20VIP%20Auto-Uploader%20Suite%20(Advance%20Booking%2070%25%20OFF%201-Year%20Plan%20RS%205000)%20book%20karna%20hai.",
    rating: 5.0,
    reviewsCount: 190,
    shortDesc: "Automated desktop publisher with bundled Chromium, Gemini AI captions, multi-page routing, micro-scheduling, and 24/7 continuous looping.",
    longDesc: "The flagship enterprise Facebook automation suite engineered for high-volume page managers, agencies, and viral video creators. Combines an internal Chromium browser, Google Gemini AI captioning, automated pre-downloading, and an unattended 24/7 loop engine with zero manual babysitting.\n\n🔥 ADVANCE BOOKING EXCLUSIVE: Get 70% OFF on the 1-Year Enterprise Plan for only RS 5,000 (Standard RS 16,500). Project completely finished and releasing within 7 days!",
    badges: ["70% OFF ADVANCE BOOKING", "1-YEAR PLAN: RS 5000", "LAUNCHING IN 7 DAYS", "WHATSAPP BOOKING"],
    features: [
      "🔥 Advance Booking Special: 70% OFF on 1-Year Full Access Plan (RS 5,000 only)",
      "🚀 Project Launch: 100% Completed & Releasing Within 7 Days",
      "Multi-Page Auto Discovery & Profile Switching with Zero Re-login",
      "Reel-by-Reel Micro-Scheduling: Configure custom publishing dates and hours",
      "Google Gemini AI Viral Captions & Dynamic Hashtag Generator",
      "Auto-Download & Video Sanitizer: Ingest from folders or links directly",
      "Embedded Chromium Engine with humanized mouse curves and anti-detection",
      "Continuous 24/7 Loop Publisher with auto-restart and failover recovery"
    ],
    techStack: ["Python", "Chromium Engine", "Playwright Automation", "Flask Backend", "PyWebView GUI", "Google Gemini API"],
    actionType: "advance_booking"
  },
  {
    id: "jaun-android-downloader",
    title: "Jaun Video & Clips Downloader",
    subtitle: "Mobile Android (.APK) — HD Video & Precision Reel Clipper",
    category: "android",
    subCategory: "mobile",
    type: "Android Mobile Application (.APK)",
    price: "UPCOMING",
    isFree: false,
    isUpcoming: true,
    isFeatured: true,
    version: "v1.0.0 APK Coming Soon",
    icon: "assets/icons/android/logo.jpg",
    rating: 5.0,
    reviewsCount: 165,
    shortDesc: "High-speed Android APK for downloading videos & creating precision clips from Facebook, Instagram, YouTube, and TikTok without watermarks.",
    longDesc: "Official upcoming Android APK release of Jaun Video & Clips Downloader. Download full HD/4K videos and Reels directly to your Android device, or use the built-in precision Clipper to extract exact 15s to 60s viral highlights on the go. Features background downloading, one-tap sharing to WhatsApp and Facebook, hardware-accelerated video rendering, and zero watermark branding.",
    badges: ["UPCOMING", "ANDROID APK", "CLIP CUTTER", "NO WATERMARK"],
    features: [
      "Built-in Precision Clip Cutter: Trim & save any 15s–60s segment instantly",
      "Full 1080p & 4K 60FPS Video Downloads with Zero Watermark",
      "Supports Facebook Reels, YouTube Shorts, TikTok & Instagram",
      "Native Android Background Download Engine with Speed Booster",
      "1-Tap Instant Share to WhatsApp Status, Facebook & Galleries",
      "Ultra-Smooth Dark Obsidian Mobile Interface Optimized for Touch"
    ],
    techStack: ["Kotlin", "Android SDK", "FFmpeg Android", "ExoPlayer", "yt-dlp Mobile"],
    actionType: "upcoming"
  }
];

if (typeof window !== 'undefined') {
  window.JAUN_STORE_DATA = JAUN_STORE_DATA;
}
